### ISSUE TITLE
Add GNOME 46 support

### ISSUE THREAD

**Issue by Daniikk1012** [kazysmaster/gnome-shell-extension-disable-unredirect#31]
GNOME 46 is now available on some distros, could you please update the extension to work on them? It will probably just require changing the metadata.

**Comment by ryanmusante** [comment]
Is this even required for Wayland?

**Comment by Daniikk1012** [comment]
I don't know about Wayland, I have NVIDIA, so I have to use X.org. Initially I used the extension to prevent tearing when screen recording gameplay, but didn't notice any tearing while playing. Now I am noticing the tearing even while playing. The extension helps with that, as it forces VSync even for fullscreen apps.

**Comment by kazysmaster** [comment]
I've merged contributed PR, pls test, will upload the extension to extensions.gnome.org soon.

**Comment by Daniikk1012** [comment]
To be honest, I am not able to reproduce the tearing (Maybe it wasn't even there, and it was just me being crazy), but the extension doesn't break the shell, so it should be fine.
