### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by willforde** [kazysmaster/gnome-shell-extension-disable-unredirect#9]
With the recent update to Gnome 3.30 on Arch Linux the `Meta.disable_unredirect_for_screen` command no longer exists. Do you know if it has been renamed or is that it for disable unredirect.

Thank you.

**Comment by NicoHood** [comment]
@jnsh Could you maybe help here?

**Comment by willforde** [comment]
This issue has already been fixed in the Pull request #10
The command has been renamed to `Meta.disable_unredirect_for_display`

**Comment by NicoHood** [comment]
I am confused. Why doesnt the PR appear in the history?
https://github.com/kazysmaster/gnome-shell-extension-disable-unredirect/commits/master

@kazysmaster Would you mind tagging a new release?

**Comment by willforde** [comment]
The PR has not being merged yet.
